GET http://localhost:8080/employee/add?firstName=Ivan&lastName=Ivanov

###
GET http://localhost:8080/employee/add?firstName=Ivan&lastName=Popov

###
GET http://localhost:8080/employee/add?firstName=Ivan&lastName=Sidorov

###
GET http://localhost:8080/employee/find?firstName=Ivan&lastName=Ivanov

###
GET http://localhost:8080/employee/remove?firstName=Ivan&lastName=Ivanov

###
GET http://localhost:8080/employee/showEmployees